/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.ibilis.booterone;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.TiApplication;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.BroadcastReceiver;
import android.app.PendingIntent;
import android.view.KeyEvent;



public class KioskService extends Activity
{
	@Override
	public boolean onKeyDown(int keyCode, KeyEvent event) {

		if ((keyCode == KeyEvent.KEYCODE_HOME)) {
	
		return true;
	
		}
//		switch (keyCode) {
//	    case KeyEvent.KEYCODE_VOLUME_UP:
//	        if (action == KeyEvent.ACTION_DOWN) {
//	            //TODO
//	        }
//	        return true;
//	    case KeyEvent.KEYCODE_VOLUME_DOWN:
//	        if (action == KeyEvent.ACTION_DOWN) {
//	            //TODO
//	        }
//	        return true;
//	    default:
//	        return super.dispatchKeyEvent(event);
//	    }
	
		// if (keyCode == KeyEvent.KEYCODE_BACK) {
	
		// //Intent nextFlow = new Intent(this, AppActionActivity.class);
	
		// Intent nextFlow = new Intent(this, AppActionDropDownActivity.class);
	
		// startActivity(nextFlow);
	
		// return true;
	
		// }
	
		return super.onKeyDown(keyCode, event);
//		return true;

	}
}